{{- if .Values.httpService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "development-environment.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "development-environment.workloadLabels" . | nindent 4 }}
  annotations:
    {{- include "development-environment.policyAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.httpService.type }}
  selector:
    {{- include "development-environment.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.httpService.port }}
      targetPort: http
      protocol: TCP
{{- end }}
